// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyU0n0_bATmznP9esjs3TgX6gv679EKGg',
    appId: '1:564336449826:web:6d5cb6bc5f554cc97d6d7b',
    messagingSenderId: '564336449826',
    projectId: 'workoutpet',
    authDomain: 'workoutpet.firebaseapp.com',
    storageBucket: 'workoutpet.appspot.com',
    measurementId: 'G-4ZT59Y6PYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHvChbHAiHyQPp2Rt7j6icZlo5X3KKyIg',
    appId: '1:564336449826:android:a811e93efba5b9f57d6d7b',
    messagingSenderId: '564336449826',
    projectId: 'workoutpet',
    storageBucket: 'workoutpet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAqoj6QrxAK4515LYCXK4k-oUOTK31fKw',
    appId: '1:564336449826:ios:dca05877b4044a0f7d6d7b',
    messagingSenderId: '564336449826',
    projectId: 'workoutpet',
    storageBucket: 'workoutpet.appspot.com',
    iosClientId: '564336449826-opsob62kji9jfu0k0urkakcv0ujpum6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutpet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAqoj6QrxAK4515LYCXK4k-oUOTK31fKw',
    appId: '1:564336449826:ios:dca05877b4044a0f7d6d7b',
    messagingSenderId: '564336449826',
    projectId: 'workoutpet',
    storageBucket: 'workoutpet.appspot.com',
    iosClientId: '564336449826-opsob62kji9jfu0k0urkakcv0ujpum6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutpet',
  );
}
